name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:

  flutter_otp_text_field: ^1.1.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  timezone: ^0.9.0
  get: ^4.6.6
  flutter_local_notifications: ^18.0.1
  intl: ^0.18.0
  shared_preferences: ^2.3.3
  video_player: ^2.5.1
  file_picker: ^5.2.7
  percent_indicator: ^4.2.4
  http: ^1.2.2
  dio: ^5.7.0
  ##image_picker: ^1.1.2
  clock: any
  url_launcher: ^6.1.5
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_analytics: ^11.3.6
  firebase_remote_config: ^5.2.0
  firebase_messaging: ^15.1.6
  api_request: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_institute.png
    - assets/Facebook.png
    - assets/Google.png
    - assets/logo2.png
    - assets/Course.png
    - assets/MediaFoundation.png
    - assets/MediaFoundation1.png
    - assets/MediaFoundation3.png
    - assets/jazz.png
    - assets/mastercard.png
    - assets/visa.png
    - assets/MaskGroupFile.png
    - assets/background.png
    - assets/certificate.png
  fonts:
      - family: Jost
        fonts:
          - asset: fonts/Jost-Regular.ttf
          - asset: fonts/Jost-Bold.ttf
            weight: 700
